### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Scmuuul** [Zydratex/Gotcha#11]
So I am trying to do the downloading process, and I am on the step where I authorize the bot. However, the bot I am authorizing is the gotcha bot 1 bot that I made, and is not Gotcha Scraper. Also, when I press start on the image scraper it does not do anything, and the image folder does not contain anything.

**Comment by OniSensei** [comment]
I updated the bot and its steps in the readme today. If you are having issues during setup please message me on discord DefaulT#2648.

Without a specific issue i am closing this thread. @Scmuuul
