### ISSUE TITLE
Error when pokemon is detected.

### ISSUE THREAD

**Issue by GiGaMo24-ZZ** [Zydratex/Gotcha#12]
I dont know whats wrong but I got an error message

![Screenshot_1](https://user-images.githubusercontent.com/52581921/61233555-5fa8a700-a763-11e9-8e4e-9c1918ffcf95.png)

and after that it work fine and catching pokemon, but later it will start to catch only one type of pokemon. for me its gothorita. and i miss a tapu lele because of this. Rip

**Comment by OniSensei** [comment]
Thank you for this. Not sure what the error is exactly, next time please copy the contents of the details and paste those, those will give a line number to where the error is generated from. It looks as tho it is happening during the stats page updater. I will look into this.

Does this happen right away? Or does this happen after the bot has been running for a while?

It is some kind of graphics bug for loading an image so it is likely the sprite preview having issues, tho not sure why this would restrict your catching / identifying.

**Comment by GiGaMo24-ZZ** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
   at System.Drawing.Image.Save(String filename)
   at Gotcha.frmMain.statsTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Gotcha
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/.../Desktop/Poke%20Bot/Gotcha.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


And this happen right away after it detect the pokemon. 

i dont know why. the 1st pokemon that it detect wrong was pikipek. later, all the pokemon it saw is determined as gothorita. tho i might say the pikipek and gothorita in my img album was almost the same. 

im going back to v1.0.0.12 until new update.

**Comment by OniSensei** [comment]
>See the end of this message for details on invoking  ...

@GiGaMo24 can you post screen shots of your img, img/cache folder, just an overview doesn’t matter where. 

Also try running the bot as admin, it’s having issues saving the image 

Possibly might be an issue with your img folder, prior to this new release if your gotcha scraper was running in discord while somebody else was doing the same it would sometimes save the image with the wrong name; like saving ditto screen shot as pikachu.png for example.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GiGaMo24-ZZ** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/52581921/61237426-0776a280-a76d-11e9-8fb7-0f98fcf3f597.png)
![Screenshot_3](https://user-images.githubusercontent.com/52581921/61237432-0ba2c000-a76d-11e9-99fa-fef640184da0.png)

I already been running the bot as admin after v1.0.0.12 released. and no i didnt think it was the image save problem either. since i always stop the bot if the image are wrong. so i would know if the name is wrong for the save image.

**Comment by OniSensei** [comment]
Interesting. Give me a moment to look into this.

**Comment by OniSensei** [comment]
So the error says that in the stats timer it cant save the image. 

The code is in frmMain.vb under statsTimer.tick()
```vbnet
                If File.Exists(imgPath & "\cache\icon\" & pkmnNew.ToLower & ".gif") Then
                    pkmnPreview.BackgroundImage = Image.FromFile(imgPath & "\cache\icon\" & pkmnNew.ToLower & ".gif")
                Else
                    Dim url As String = "https://img.pokemondb.net/sprites/sun-moon/icon/" & pkmnNew.ToLower & ".png"
                    Dim tClient As WebClient = New WebClient
                    Dim timage As Bitmap = Bitmap.FromStream(New IO.MemoryStream(tclient.DownloadData(url)))

                    timage.Save(imgPath & "\cache\icon\" & pkmnNew.ToLower & ".gif")
                    pkmnPreview.BackgroundImage = Image.FromFile(imgPath & "\cache\icon\" & pkmnNew.ToLower & ".gif")
                End If
```

This problem can occur for a couple of reasons.

* It is possible your hard drive is full?
* The directory could be incorrect for some reason
   - Please insure the bot is running in a folder with 2 sub folders named:
      - img & logs
        - Inside of img should be the sub folder cache
* You might not have write permissions to the folder for some reason
   - Insure the folder containing the bot is somewhere like the desktop and not directly in C:\ or another write protected directory

There might be something I can do in the code to prevent something like this and I will look into it.

Its possible you're unable to load the image because your system is still trying to save the file and the program is moving to fast. Since the picture box on the form uses the same image it is attempting to save. To fix this I can just declare a new Bitmap variable and call that for the picture box then save the original from stream.

**Comment by OniSensei** [comment]
@GiGaMo24 Possibly fixed the issue. Will need you to test, I updated the release zip to include the new fix. Was a simple change of code.

[v1.0.0.13 - Bug fix](https://github.com/OniSensei/Gotcha/releases/tag/1.0.0.13)
Try it and let me know

**Comment by GiGaMo24-ZZ** [comment]
@OniSensei i can tell you that my drive isnt full yet. and all the folder you mention is in the right place and the file also are put on desktop.

and the fix didn't work. the bot detected kommo-o as lurantis. the thing is, this is the 2nd pokemon after the bot start. 1st spawn is cleffa and it did get it.

I've observed the info at home tab, it stuck at some pokemon name before it give random catch name and it didn't show any pokemon img while searching at the right conner of it. only a question mark.

**Comment by OniSensei** [comment]
Delete the images in img/cache/icon.

If it tried to catch kommo-o as lurantis, look at lurantis.png in /img/ it prob is kommo-o tbh.

The '?' icon is used as a placeholder for images it cant find. i.e alola forms, also it starts with the '?' and returns to the '?' after it finds the pokemon.

**Comment by GiGaMo24-ZZ** [comment]
there's icon folder in cache? or did u mean the .gif file? i should delete all of it?

![Screenshot_4](https://user-images.githubusercontent.com/52581921/61258574-006d8580-a7a9-11e9-87f7-c3282d0193a5.png)

I can assure you the img is fine. the same can be said for the previous. gothorita img also fine. i miss 10+ pokemon when i found out this bug. but the bot still detected all the pokemon as gothorita. 

Ahh. i see. but it seem like it stuck after searching for a while. the last time it tried to detect kommo-o it stuck at alolan exeggcutor. and didnt change at all until it detected kommo-o as lurantis.

**Comment by OniSensei** [comment]
Delete the .gif files in cache/icon 
And thats interesting, what does kommo-o look like?

**Comment by GiGaMo24-ZZ** [comment]
Already did. but the same error still came up. 

![Screenshot_5](https://user-images.githubusercontent.com/52581921/61259189-acb06b80-a7ab-11e9-87d6-267816db643f.png)

here's the kommo-o

**Comment by OniSensei** [comment]
This is very strange, I would have to see it happen to know for sure what is causing this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GiGaMo24-ZZ** [comment]
I wish i could help more. 
nevertheless i will be using the previous version. It work flawlessly for me.

**Comment by OniSensei** [comment]
That was the only change with the last version to this was the image cache for this icon xD

Ill look into other possible solutions... maybe a do while loop.

**Comment by GiGaMo24-ZZ** [comment]
Ayee. then i'll wait for the new update. Thanks for the hard work.

**Comment by sweethome456789** [comment]
i do not have a single picture in the C:\Users\Downloads\Gotcha.v1.0.0.13\img\cache\icon (this is where i extracted the zip file) and also once i clicked the START option in image scrapping after getting the coordinates on bulbasours forehead it gave me a error!

**Comment by OniSensei** [comment]
@sweethome456789 please open your own issue with screenshots of the error, also, the cache is empty till it runs, it caches as it runs 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
