### ISSUE TITLE
[ERROR] Couldn't capture and compare images...

### ISSUE THREAD

**Issue by Hadasdasdas** [Zydratex/Gotcha#13]
Like 3 seconds after i press start on the bot it says that. It only sends 1 message into the general chat too, doesnt continue.

**Comment by OniSensei** [comment]
You'll have to elaborate a bit more on whats going on.

**Comment by Hadasdasdas** [comment]
sorry i was real tired when i wrote this. Last night i downloaded gotcha and imged all the pokemon over discord. after having finished the instructions and going into general and pressing start the bot sends out on spam message before sending the error message on gotcha "[ERROR] Couldn't capture and compare images..." In the meantime of having image scapped it stopped a couple times but i decided to remove those images and redo them but a few didnt work. Do i have to scrap again or what is the fix?

**Comment by GiGaMo24-ZZ** [comment]
Although i never have this error but i might can help on scrapping the image.

@Hadasdasdas it also stop on me sometime when scrapping. but it nevertheless didn't bug out the catching process at all as long the scrap image is the right one. if there's a faulty/grey image, just delete melmetal.png and those faulty image then start scrapping again. no need to redo all of them. just the faulty one. 

iirc @OniSensei has said there have been reported that some image might have wrong pokemon name or wrong image of pokemon. so just check for those. delete them and scrap again.

**Comment by OniSensei** [comment]
@Hadasdasdas  what @GiGaMo24 has said is generallty correct.

If it stops and you get that error message its because the image taken is not the same as whats on the screen now. This is likely because the image scraper took a picture of the pokemon before the image was loaded.

Go through the img folder and delete any ones that are completely gray or that dont have a pokemon image in them, restart the scraper and it should pickup where it left off or re-scrape the images that were deleted. Please keep in mind for pokemon like dratini, you can run the step for F5 to set coordinates anytime.

**Comment by Hadasdasdas** [comment]
i know but the problem ls whenever i do that i can an unknown error i cant remember what it said i cant get on my laptop rn but when i deleted mel metal and those who were off it gave me a weird error. ill try it again tonight

**Comment by Hadasdasdas** [comment]
![image](https://user-images.githubusercontent.com/52942525/61331031-52ea8880-a821-11e9-8b89-4af68aa98308.png)
This is the error i get. I have checked every pokemon image so that there are no more greys only. I have concerns about 
![A pokemon encounter](https://user-images.githubusercontent.com/52942525/61331055-68f84900-a821-11e9-9add-868d6b870806.png)
![A level up](https://user-images.githubusercontent.com/52942525/61331058-6990df80-a821-11e9-93da-fd4ef7c8d5ba.png)
![A pokemon evolution](https://user-images.githubusercontent.com/52942525/61331059-6990df80-a821-11e9-960a-2115c0d28605.png) these 3. Are they important? are they done correctly? does it have an impact? I would know no other problem because every image is correct.

**Comment by Hadasdasdas** [comment]
it looks like i had to rename the pictures to a specific name and now it works. the bot is sending messages very slowly thats the only thing that seems off now. I will close this now until further notices

**Comment by Hadasdasdas** [comment]
ignore that. well i fixed the issue of it not working by renaminf the pictures above accordingly. now that the bot is working another problem occurs. It is sooooo slow and barely send out messages and it takes up to 210 seconds to identify a pokemom. any ideas?

**Comment by GiGaMo24-ZZ** [comment]
@Hadasdasdas if im correct, the only important img of those 3 is the spawn message. thats the only thing that the bot detected to know a new pokemon spawn. u need to take your own screenshot of 50x50. the level up and evolve message are just use in the stats and wont have anything to do to catch a pokemon.

for slow message, how many ms did you use before sending new message? it is the interval in the basic tab.

**Comment by OniSensei** [comment]
Also depending on the Pokémon, like bulbasaur is at the beginning of the list so it will be detected super fast, however if something like marshadow who’s at the end of the list it will take longer.

And for sending message that is dependent on the interval in basic settings 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hadasdasdas** [comment]
i tried arounf with the MS but it really spams the same intervals every time fairly slow. sometimes even stopping inbetween. its probably because of this slow low effort laptop.
