### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by kayehx** [Zydratex/Gotcha#3]
I get error messages whenever a pokemon appears and only when pokemon appears. I believe the problem is something with the detection. I've tried testing the image scraper in the advanced options and it always successfully matches the pokemon. However when the bot is running it will only spam and when it gets to an image it sends this error window: 
![image](https://user-images.githubusercontent.com/51402285/58945392-a3f26180-8738-11e9-9e4d-e5b740235ed0.png)

here is the log page too: 
![image](https://user-images.githubusercontent.com/51402285/58945449-ba002200-8738-11e9-8566-36db7fd8a4b9.png)

**Comment by OniSensei** [comment]
I have updated the release and the readme with clearer instructions.
