### ISSUE TITLE
Error catching

### ISSUE THREAD

**Issue by ghost** [Zydratex/Gotcha#4]
after starting the bot spam works fine but when a poke spawns it throws this error, the pokemon listed is whatever is first selected in the list. image testing says it works@Zydratex
[https://imgur.com/a/yEZjxx7](url)

**Comment by Blxckmage** [comment]
yup, this is a struggle

**Comment by ghost** [comment]
> 
> 
> yup, this is a struggle
You know of any others working @sagapg

**Comment by OniSensei** [comment]
You will need new screen shots for the bot.

**Comment by OniSensei** [comment]
I have updated the release and the readme with clearer instructions.
