### ISSUE TITLE
Image Scrapper not working

### ISSUE THREAD

**Issue by GiGaMo24-ZZ** [Zydratex/Gotcha#9]
Ok. the image scrapper thing didnt work for me due to it didnt get the coordinate of x and y. Already followed the instruction and even create the separate channel for this, clicking F5 only do nothing for me. nothing can change the coordinate. even tried manually input the x and y but the image still the same. i did tried start it and it did catch a new image. so the problem probably due to the capturing the screen. Below is the image i captured.

![Melmetal](https://user-images.githubusercontent.com/52581921/60765722-5a978800-a0d1-11e9-8c07-69bacf37e694.png)

**Comment by OniSensei** [comment]
Ive updated the application again as a user on discord pointed out a small bug. It has since been fixed, please redownload version 1.0.0.12
